### ISSUE TITLE
Laravel development

### ISSUE THREAD

**Issue by cmosguy** [neo4j-php/neo4j-php-client#107]
Hey there. Do you guys need help with getting this ready for Laravel?

it was mentioned in this video: https://youtu.be/qwz5XVtbfSY

**Comment by transistive** [comment]
Hello @cmosguy,

Thank you for reaching out!

We can definitely use help! Right now we are working on modernizing [NeoEloquent](https://github.com/Vinelab/NeoEloquent), but it might be even simpler to have a basic package to integrate the client or driver as well.

What do you think?

Kind regards,

Ghlen

**Comment by transistive** [comment]
Closed due to inactivity
