### ISSUE TITLE
Error using HTTP protocol over linux

### ISSUE THREAD

**Issue by joseraul** [neo4j-php/neo4j-php-client#109]
**Describe the bug**
We are having problems connecting the driver using the HTTP protocol over a Linux machine.

**To Reproduce**

This works (with BOLT): 
```
        $formatter = new SummarizedResultFormatter(OGMFormatter::create());
        $client = ClientBuilder::create()
            ->withDriver('default', 'bolt://@db_neo4j:7687', $this->getAuth())
            ->withFormatter($formatter)
            ->build();
```
but this does not work (with HTTP)
```
        $formatter = new SummarizedResultFormatter(OGMFormatter::create());
        $client = ClientBuilder::create()
            ->withDriver('default', 'http://@db_neo4j:7474', $this->getAuth())
            ->withFormatter($formatter)
            ->build();
```
We were using another driver to connect to neo4j via HTTP, so our guess is that the database per se it's correctly configured. However, any connection that we try to do to the database produces the following neo4j error:

```
db_neo4j    | 2022-02-07 18:40:33.215+0000 ERROR The RuntimeException could not be mapped to a response, re-throwing to the HTTP container Unable to construct bolt discoverable URI using 'null' as hostname: Expected scheme-specific part at index 5: bolt:
db_neo4j    | org.neo4j.graphdb.config.InvalidSettingException: Unable to construct bolt discoverable URI using 'null' as hostname: Expected scheme-specific part at index 5: bolt:
db_neo4j    |   at org.neo4j.server.rest.discovery.DiscoverableURIs$Builder.add(DiscoverableURIs.java:133)
db_neo4j    |   at org.neo4j.server.rest.discovery.DiscoverableURIs$Builder.overrideAbsolutesFromRequest(DiscoverableURIs.java:168)
db_neo4j    |   at org.neo4j.server.rest.discovery.DiscoveryService.getDiscoveryDocument(DiscoveryService.java:64)
db_neo4j    |   at org.neo4j.server.rest.discovery.DiscoveryService.get(DiscoveryService.java:79)
db_neo4j    |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
db_neo4j    |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
db_neo4j    |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
db_neo4j    |   at java.lang.reflect.Method.invoke(Method.java:498)
db_neo4j    |   at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
db_neo4j    |   at om.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
d
....
```

**Expected behavior**
That it can connect :)

**Desktop (please complete the following information):**
 - Library version: 2.4.4
 - Neo4j Version: 3.5
 - PHP version: 8.0.15
 - OS:  Ubuntu 20.04.3 LTS

**Additional context**
It is worth saying that in Windows both protocol works, the HTTP and BOLT.

Do you have any idea about what might happen?

Thanks!

**Comment by transistive** [comment]
Very interesting stuff! Thank you for reaching out :pray: 

I can check it tomorrow. In the meantime, can you confirm it works without the `@` symbol?

`->withDriver(default', 'http://db_neo4j:7474', $this->getAuth())`

**Comment by joseraul** [comment]
The same behaviour with or without the `@`

**Comment by Johnhundred** [comment]
To add to @joseraul 's information: From our continued testing, this seems to be specific to using neo4j 3.5 in a docker container. The setup for the container (using docker compose) is as follows:

`  database:
    image: neo4j:3.5
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_conf:/conf
      - ./neo4j_plugins:/plugins
    environment:
      - "NEO4J_dbms_active__database=graph.db"
    container_name: db_neo4j`

**Comment by transistive** [comment]
Hi everyone,

My apologies for the delay. I've tried several setups on several Linux distro's and am not able to reproduce the problem. If you are interested, I can schedule a digital meeting to look at it together?

My email is ghlen@pm.me

**Comment by joseraul** [comment]
Hi @transistive !
I'm so sorry I'm answering so late.
Finally, we discarded the bug as the problem was in our environment. We didn't figure out where, but after changing the environment the bug was gone.
Cheers
