### ISSUE TITLE
Is this package production ready?

### ISSUE THREAD

**Issue by MarkAdell** [neo4j-php/neo4j-php-client#110]

**Comment by fbiville** [comment]
It's been successfully tested against production Neo4j systems (such as AuraDB) and people are using the project in production.
What specific concerns do you have in mind?

**Comment by transistive** [comment]
I can confirm this package is production ready. I am aware of a few professional clients, including myself, that are using the library without issue in production :ok_hand: 

If any regressions slip through the CI and appear in new releases, we usually fix them within 24 hours.

**Comment by MarkAdell** [comment]
@fbiville @transistive 

Thanks for your replies! No specific concerns, I just wanted to make sure it's tested on production as we are going to use it in our company.
