### ISSUE TITLE
BoltOGMTranslator does not correctly return wgs84-points.

### ISSUE THREAD

**Issue by wgevaert** [neo4j-php/neo4j-php-client#114]
**Describe the bug**
When the Bolt protocol returns a wgs84 or wgs843D point, the default formatter changes all points into cartesian points.

**To Reproduce**
1. In a Neo4j database, make a node/relation with a property that has a (2d/3d) wgs84 point as a value, e.g.
    CREATE (n:TEST {prop1: point({longitude: 3.03, latitude: 5.5, crs: 'WGS-84'})});
3. Use the default settings to connect to that database with bolt, and request that property, e.g.
    ClientBuilder::create()->withDriver('bolt', 'bolt://admin:password@localhost:7687')->withDefaultDriver('bolt')->create()->run(
        'MATCH (n:TEST) RETURN n.prop1'
    )->first();

**Expected behavior**
The returned property should be encapsulated in a WGS84Point (or WGS843DPoint) instead of a Cartesian(3D)Point.

**Comment by wgevaert** [comment]
Okay I did some more digging, and to me it seems that the implementation of `WGS84`(`3D`)`Point` is somewhat weird.

In particular, it contains both `longitude` and `x` resp. `latitude` and `y` (resp. `height` and `z` for 3D) values, where these should always be pairwise the same.

Could these be united into one? the functions `getLatitude` and `getLongitude` could then just be aliasses for `getX` and `getY`.

**Comment by transistive** [comment]
Very interesting! It appears the HTTP protocol does it correctly. Thank you for pointing this out.

When looking at the bolt documentation here: https://7687.org/packstream/packstream-specification-1.html, It appears to not understand WGS84. I'll ask around in the driver team to see what's up and if we can do something about it!

Speak to you soon :+1:

**Comment by wgevaert** [comment]
I think the bolt protocol does support WGS84, in the following way:
* `Cartesian point`: It returns an `x`, `y` and `srid=7203`. For 3D it returns `srid=9157` and an additional `z`.
* `WGS 84`: It returns an `x` (aka `longitude`), `y` (aka `latitude`) and `srid=4326`. For 3D it returns `srid=4979` and an additional `z` (aka `height`).

If you don't mind, I'll take the liberty to make a pr.

**Comment by wgevaert** [comment]
I made a pr 😄

**Comment by transistive** [comment]
Great work! It's merged and will be available in version 2.5.0 :hand:
