### ISSUE TITLE
When update to 2.5.0 transactions fails

### ISSUE THREAD

**Issue by vzenix** [neo4j-php/neo4j-php-client#117]
**Describe the bug**
Today I update the library and some methods fails when I use transactions.

**To Reproduce**
1. Create client with neo4j scheme 
2. Open transaction 
3. Commit transaction

**Expected behavior**
The commit fail with the message

Neo4j errors detected. First one with code "Neo.ClientError.Request.Invalid" and message "Message 'COMMIT' cannot be handled by a session in the TX_STREAMING state.

Fail all transactions, when I do a downgrade of library to version 2.4.4, it's run correctly.

**Code**
`
        $transaccion = $client->beginTransaction();

        try {
            $transaccion->run($queryCrear, $param);
            $transaccion->run($queryRelaciones, $param);
            $transaccion->commit();
        } catch (\Exception $ex) {
            try {
                $transaccion->rollback();
            } catch (\Exception $exRollback) {
                // Save error of rollback and notify the administrator
            }

            throw $ex;
        }
`

**Desktop (please complete the following information):**
 - Library version: Fail in 2.5.0, run in <=2.4.4
 - Neo4j Version: 3.5.14
 - PHP version: 7.4
 - OS: Fedora

**Additional context**
Thanks.

**Comment by transistive** [comment]
Hello @vzenix,

Thank you for creating the issue. It appears you have found a regression.
I will circle back to this bug tonight and will fix it as soon as possible.

Kind regards,

Ghle

**Comment by vzenix** [comment]
> Hello @vzenix,
> 
> Thank you for creating the issue. It appears you have found a regression. I will circle back to this bug tonight and will fix it as soon as possible.
> 
> Kind regards,
> 
> Ghlen

**Comment by transistive** [comment]
Fixed in version 2.5.1

**Comment by vzenix** [comment]
> Fixed in version 2.5.1

It's work, thanks
