### ISSUE TITLE
HttpOGMFormatter throws exception on certain inputs

### ISSUE THREAD

**Issue by wgevaert** [neo4j-php/neo4j-php-client#120]
**Describe the bug**
When using an http client with the default http OGM formatter, for some queries the results do not seem to be formatted correctly.
In particular, the following gave me a `CypherMap` where I expected a `WGS84Point`:

**To Reproduce**
**EDIT** The code below is now working. However, the issue still occurs for the query `RETURN {item2:point({x:0,y:0})} AS list`, because of the limitations of the Http api.
```php
<?php

require_once './vendor/autoload.php';

// Create an http client
$client = \Laudis\Neo4j\ClientBuilder::create()->withDriver(
    'http',
    'http://localhost:7474',
    Laudis\Neo4j\Authentication\Authenticate::disabled()
)->withDefaultDriver('http')->build();

// Run the problematic query
$result = $client->run(
       // Make/match a testnode with a lot of rubbish properties
       'MERGE (n:TESTNODE ' .
           '{loc: point({srid:4326, x:3.03, y:5.5}),float: 5.0,int: 5}' .
       ')' .
       // Return all the properties.
       // Bug does not seem to occur when only returning a single property
       'RETURN n.int AS int, n.float AS float, n.loc AS loc'
   );

// one expects this to be a Laudis\...\WGS84Point, but it is a CypherMap
var_dump($result->first()['loc']);
```

I couldn't really pinpoint what goes wrong here. If I read [this line of testing code](https://github.com/neo4j-php/neo4j-php-client/blob/bb82279d4c4cfd8ccef801490c58dd33f6053373/tests/Integration/OGMFormatterIntegrationTest.php#L558) correctly, it seems to be explicitly stating that what I want is impossible. However, I would really like something like this to work.

**Desktop:**
 - Library version: dev-main (`89e323f`)
 - Neo4j Version: 4.3.3
 - PHP version: 7.4.24
 - OS: MacOS

**Comment by wgevaert** [comment]
Furthermore, the following query throws an exception:

```php
// Run the problematic query
$result = $client->run(
    // Make/match a testnode with a lot of rubbish properties
    'MERGE (n:TESTNODE ' .
        '{' . 
            'int: 5,' .
            'loc: point({srid:4326, x:3.03, y:5.5})' .
       '}' .
    ')' .
    // Return all the properties.
    'RETURN ' .
        'n.int AS int, ' .
        'n.loc AS loc'
);
```

**Comment by wgevaert** [comment]
Neo4j version 4.2+ has support for the [jolt format](https://neo4j.com/docs/http-api/4.2/actions/result-format/#_jolt), which might be interesting to support. However, that would remove compatibility with Neo4j <4.2 and requires quite some work.
Maybe I'll make a new issue for the jolt format.

**Comment by wgevaert** [comment]
I believe I found the problem, I made a PR.

**Comment by transistive** [comment]
Hello @wgevaert,

Thank you for Issue and PR. I am reviewing it now.

In the meantime, you can create an issue requesting the JOLT feature. It is definitely preferable to the legacy HTTP API, as it contains major limitations.
