### ISSUE TITLE
Support Jolt for Http return type

### ISSUE THREAD

**Issue by wgevaert** [neo4j-php/neo4j-php-client#122]
**Is your feature request related to a problem? Please describe.**
The current HttpOGMTranslator that is used by the (default) OGMFormatter has a limited, convoluted & error-prone way of inferring the datatype of an object based on the metadata that is returned alongside the values.

The Jolt protocol, introduced in Neo4j 4.2 and up, includes the datatype information in the results json itself. This makes inference of datatypes simpler and less error-prone.

**Describe the solution you'd like**
1. `Http\RequestFactory::createRequest` should set the `Accept`-header to a different value, see [the neo4j documentation](https://neo4j.com/docs/http-api/4.2/actions/result-format/#_jolt), sections 2.1&2.2 for the possible values & options.
    Maybe the http Accept header can be injected from a `Contracts\FormatterInterface`, I think it makes sense to give the formatter some control over the returned values.
2. The `OGMFormatter` (in particular the `HttpOGMTranslator`) should be refactored/rewritten to use the jolt protocol.
3. The supported versions of neo4j should not include <4.2 anymore, or the current HttpOGMTranslator should be included as a legacy formatter for those versions of Neo4j.

**Additional context**
This idea came up on discussion of issue #120 . Some more remarks about this are on pull request #121

**Comment by transistive** [comment]
Fixed in #123
