### ISSUE TITLE
Dumping a summarized result may error

### ISSUE THREAD

**Issue by transistive** [neo4j-php/neo4j-php-client#125]
**Describe the bug**
Apparently, references don't play nicely with certain libraries. When an unconsumed summarized result gets dumped, it may crash.

**To Reproduce**
I run a query and then want to dump the result to see it, but an error occurs
Steps:
1. Create client
2. Run a query then dump the results
```php
$result = $client->run("MATCH (n:Node) SET n.testing = 'hello' RETURN n");
dump($result);
```
This error is produced
```
In VarCloner.php line 108:
                                                                                                                                                                                                 
  Type error: Cannot assign Symfony\Component\VarDumper\Cloner\Stub to reference held by property Laudis\Neo4j\Databags\SummarizedResult::$summary of type ?Laudis\Neo4j\Databags\ResultSummary
```
This happens for both transactions and direct runs.
If I dump `dump($result->getSummary());` it works and prints the summary, is this an intended behavior? I know this is not a critical issue, but I thought I would mention it :sweat_smile: 

Note: something weird happens with the run, if a result is expected to be return (there is a return in the query), just the run itself doesn't run the query, but `getSummary()` or `toArray()` do, so this
```php
$result = $client->run("MATCH (n:Node) WITH * CALL apoc.util.sleep(2000000) RETURN n");
```
finishes instantly, indicating that the query is not being ran or something.
But this
```php
$result = $client->run("MATCH (n:Node) WITH * CALL apoc.util.sleep(2000000) RETURN n");
$summary = $result->getSummary();
```
or this
```php
$result = $client->run("MATCH (n:Address) WITH * CALL apoc.util.sleep(2000000) RETURN n");
$array = $result->toArray();
```
Actually run the query and perform the sleep properly, is this behavior intended?

**Expected behavior**
The dump should work and return either null or the summary in place of the reference.

**Additional context**
Taken from #124

**Comment by noureldin-khaled** [comment]
Hey @transistive :wave: 

Unfortunately, I'm still running into the same exact issue
```php
$result = $client->run("MATCH (n:Node) SET n.testing = 'hello' RETURN n");
dump($result);
```
Still gives the same error
```
In VarCloner.php line 108:
                                                                                                                                                                                                 
  Type error: Cannot assign Symfony\Component\VarDumper\Cloner\Stub to reference held by property Laudis\Neo4j\Databags\SummarizedResult::$summary of type ?Laudis\Neo4j\Databags\ResultSummary  
```

is there something I'm missing? :thinking: 

Client version: 2.6.1
Neo4j version: 4.4.3
