### ISSUE TITLE
Use bookmarks in basic formatter

### ISSUE THREAD

**Issue by transistive** [neo4j-php/neo4j-php-client#140]
**Is your feature request related to a problem? Please describe.**
I simply forgot to implement bookmarks if you use the basic formatter.

**Describe the solution you'd like**
Implement it like the other formatter

**Additional context**
Pointed out by the lovely folks over at issue #139, @stefanak-michal and @wgevaert

**Comment by wgevaert** [comment]
Would it be possible to set the return type of `FormatterInterface::formatBoltResult` to `CypherList` and then put the following code from `OGMFormatter` in `BoltUnmanagedTransaction`:
```php
        $result = new BoltResult(...);
        $formattedResult = $this->formatter->formatBoltResult(...,$result,...);

        $this->connection->subscribeResult($formattedResult);
        $result->addFinishedCallback(function (array $response) use ($holder) {
            if (array_key_exists('bookmark', $response) && is_string($response['bookmark'])) {
                $holder->setBookmark(new Bookmark([$response['bookmark']]));
            }
        });
```

or would this do stupid things for e.g. the summarisedresultformatter?

This way, we only use the formatter for actual formatting, and do the other not-strictly-formatter operations outside of the formatter.
