### ISSUE TITLE
Doesn't work at php 7.4

### ISSUE THREAD

**Issue by stefanak-michal** [neo4j-php/neo4j-php-client#142]
**Describe the bug**
Composer.json contains ` "php": "^7.4 || ^8.0",` but the code is using function `str_starts_with` from php>=8.

https://www.php.net/str_starts_with

https://github.com/neo4j-php/neo4j-php-client/blob/2.7.0/src/Bolt/BoltConnection.php#L33

**Expected behavior**
I expect to work on php 7.4 if composer.json is telling me so.

**Desktop (please complete the following information):**
 - Library version: 2.7.0
 - Neo4j Version: 4.4
 - PHP version: 7.4
 - OS: Windows 10

**Comment by transistive** [comment]
Hi Michal,

Did you test if it works? It includes a polyfill `symfony/polyfill-php80` in the same composer.json file. All tests work in GitHub actions.

**Comment by stefanak-michal** [comment]
oh I see. my mistake.

**Comment by transistive** [comment]
No problemo! :+1:
