### ISSUE TITLE
Query keeps running when trying to create a node violating the unique constraint

### ISSUE THREAD

**Issue by MarkAdell** [neo4j-php/neo4j-php-client#151]
**Describe the bug**

When I try to create a node violating the unique constraint, **and** return the node, the query keeps running forever.

**To Reproduce**

Create a node and add a unique constraint

```php
$client->run("CREATE (test:Test{id: '123'})");
$clinet->run("CREATE CONSTRAINT ON (test:Test) ASSERT test.id IS UNIQUE");
```
Try to re-create the node and return it

```php
$client->run("CREATE (test:Test {id: '123'}) RETURN test");
```

**Actual behavior**

The query keeps running until my php maximum execution time is reached (60 seconds)

**Expected behavior**

I expect it to throw a `Neo4jException` with code `ClientError.Schema.ConstraintValidationFailed` 

Note that it successfully throws the exception if I don't return the node 

```php
$client->run("CREATE (test:Test {id: '123'})");
```

**Desktop (please complete the following information):**
 - Library version: 2.7.0
 - Neo4j Version: 4.0.8
 - PHP version: 7.4

**Comment by stefanak-michal** [comment]
I have tested it with Bolt and get expected exception

```
PHP Fatal error:  Uncaught Bolt\error\MessageException: Node(8) already exists with label `Test` and property `id` = '123' (Neo.ClientError.Schema.ConstraintValidationFailed) 
```

It seems it will be problem with client.

**Comment by transistive** [comment]
Hello @MarkAdell,

I have tried to reproduce the problem without any success. I am currently in a location with *horrible* internet, so I had to test it with my local installation of Neo4j 4.4.

Do you have access to a newer version? Neo4j 4.0 is not officially supported any more by Neo4j anyway: https://neo4j.com/developer/kb/neo4j-supported-versions/

I will have access to better internet later during the day to test it out again.

Kind regards,

Ghlen

**Comment by MarkAdell** [comment]
Hello @transistive 

I also tested it on my local installation of Neo4j 4.4 and couldn't reproduce the issue. The issue happens on our production server with Neo4j 4.0.8, and I wasn't able to install this version locally to test it as Neo4j probably removed it. 

![image](https://user-images.githubusercontent.com/18086162/189679322-6665dec9-11a7-4416-98bd-96a564dcdd83.png)

**Comment by fbiville** [comment]
@MarkAdell Neo4j 4.0.8 is available as a Docker image, if that helps: https://hub.docker.com/_/neo4j/tags?page=1&name=4.0.8

**Comment by transistive** [comment]
So I have not been able to reproduce it. I used the community Neo4j 4.0.8 image. 

I did get an infinite loop when I tried to insert a duplicate right after building the constraint. If I wait a little while after building the constraint the error is produced correctly. This makes me believe it is Neo4j still building the schema and doing some undefined behaviour which the driver can't deal with. All other Neo4j versions work as expected.

Can you confirm it works if you build the schema and then wait a while before running the query?

Kind regards,

Ghlen

**Comment by transistive** [comment]
Closed due to inactivity and non-reproducibility
