### ISSUE TITLE
AWS Neptune Support

### ISSUE THREAD

**Issue by vicki-bns** [neo4j-php/neo4j-php-client#153]
**Is your feature request related to a problem? Please describe.**

As AWS Neptune supports openCypher and Neo4j Bolt message specification version (4.0.0), I am trying to connect to AWS Neptune as below. However, I get "Wrong Version" in handshake. I also tried to use "bolt+s" and "bolt+ssc", but it is also failed.

```php
$address = 'xxxx.com';
$port = 'port';
$conn = new \Bolt\connection\StreamSocket($address, $port);
// enable SSL
$conn->setSslContextOptions([
    'verify_peer' => true
]);
$bolt = new \Bolt\Bolt($conn);
$bolt->setProtocolVersions(4);
$bolt->build();
```

As I am not sure the configuration and connection are correct, I tried to connect to AWS Neptune via python and get the connection successfully:

```python
from neo4j import GraphDatabase

uri = "bolt://xxxxxx.com:port"
driver = GraphDatabase.driver(uri, auth=("neo4j", "neo4j"), encrypted=True)
```

May I know is it supported to connect to AWS Neptune? Thank you very much.

**Comment by stefanak-michal** [comment]
I wanted to try it with AWS Neptune in past but I didn't get free access from Amazon and I'm not going to pay for it. Sorry

**Comment by vicki-bns** [comment]
If you have interest to try with AWS Neptune, may you please leave an email that we can grant you the access of AWS Neptune? Thank you.

**Comment by stefanak-michal** [comment]
@vicki-bns that will be great. My email is stefanak.michal@gmail.com

I'll have time this Saturday to look at it if that is okay with you.

**Comment by transistive** [comment]
Hi @vicki-bns,

Thank you for your interest! 

@stefanak-michal, please ping me your findings on the bolt driver and tell me if I need to create a PR on this.

Kind regards,

Ghlen

**Comment by vicki-bns** [comment]
Hi @stefanak-michal , Sorry, we need some time to prepare another environment for that. The environment and access will be prepared before next Wednesday. We will get back to you as soon as possible.

**Comment by vicki-bns** [comment]
Hi @stefanak-michal ,

My teammate sent an email to AWS to ask about the Bolt connection with PHP. AWS replied that there is some problem on handshake. 

They changed the source codes in `Bolt.php` from 
``` php 
$this->connection->write(chr(0x60) . chr(0x60) . chr(0xb0) . chr(0x17));
$this->connection->write($this->packProtocolVersions());
```
to 
``` php 
$this->connection->write(chr(0x60) . chr(0x60) . chr(0xb0) . chr(0x17) . $this->packProtocolVersions());
```
After applying the changes, we can connect to AWS Neptune successfully. 

Thank you for your interest to integrate with AWS Neptune :) !

**Comment by stefanak-michal** [comment]
@vicki-bns that is really interesting. thanks for feedback. 

fyi https://neo4j.com/docs/bolt/current/bolt/handshake/

**Comment by vicki-bns** [comment]
Great, thanks for the effort :)
