### ISSUE TITLE
Nested Loops - process break after first internal run

### ISSUE THREAD

**Issue by Alaizabel** [neo4j-php/neo4j-php-client#154]
**Describe the bug**
I am not sure if this is really a bug in the client, it's more likely that my code has a bug - and I would be happy to understand what the problem is, maybe someone can help? 

A new Neo4J instance is made. 

![image](https://user-images.githubusercontent.com/65511333/198889000-f72b2b61-69fb-46ba-9ece-d792871c8585.png)

With a PHP script (see end of post) 11 nodes are inserted as example nodes. They have the properties Name and Nummer with random content.

![image](https://user-images.githubusercontent.com/65511333/198889177-50452f63-0ff4-4137-bbe7-29bc2d80d65b.png)

**To Reproduce**
     
         // embedding Neo4J PHP DB driver                                                              
        use Laudis\Neo4j\Authentication\Authenticate;
        use Laudis\Neo4j\ClientBuilder;

        // establish a client-object for database access (Neo4J AURA DB)
       $client = ClientBuilder::create()
           ->withDriver('TOM3',$_ENV['db_url'],Authenticate::basic($_ENV['db_username'], $_ENV['db_password']))
           ->build();

       $outerLoopQuery = "MATCH (n) return n.Nummer AS Nummer";
       $outerLoopResult = $client->run($outerLoopQuery);

       >> echo COUNT($outerLoopResult);      <--- senseless code line << 

      foreach ($outerLoopResult as $recordsOuterLoop) {

         $innerLoopQuery = 'MATCH (n) WHERE n.Nummer = '.$recordsOuterLoop['Nummer'].' return n.Name as Name';
         $innerLoopResult = $client->run($innerLoopQuery);

          foreach ($innerLoopResult as $recordsInnerLoop) {
          // do something
               echo $recordsInnerLoop['Name'].'<br>';
         }      
      }

**Expected behavior**
Expected:
Output of 11 names as a list

Problem:
Without the "senseless code line" I receive only one name as if the inner loop is run only once or the outer field contains only one recordset. 

![image](https://user-images.githubusercontent.com/65511333/198890585-c0b93115-25f6-4679-a639-6821e1560494.png)

When I try the queries in the Neo4J Browser they work fine. If the "senseless code line" is added to the code I get the excpected behaviour. Works also with other COUNT constructions e.g. $x=COUNT($outerLoopResult); - doesnt need an echo.

![image](https://user-images.githubusercontent.com/65511333/198890608-9b96cf16-1078-4e5f-9ef7-eb6876cbc591.png)

As long I use only one loop all is ok (e.g. for the creation of the random names), when I start to nest the loops as I am used to from older clients I run into this issue.

**Desktop (please complete the following information):**
 - Library version: [2.8.8]
 - Neo4j Version: [aura 4]
 - PHP version: [8.0.1]
 - OS: [Windows 10]

**Additional context**
Here is the script for generating random names:

for ($x=1;$x<=11;$x++)
{

    $initialInsertQuery = 'CREATE (n:Name) SET 
                            n.Name = "'.randomName().'",
                            n.Nummer = '.$x.'
                         RETURN n';

    $initialInsertResult = $client->run($initialInsertQuery);    
}

function randomName() {
    $firstname = array(
        'Johnathon',
        'Anthony',
        'Erasmo',
        'Raleigh',
        'Nancie',
        'Tama',
        'Camellia',
        'Augustine',
        'Christeen',
        'Luz',
        'Diego',
        'Lyndia',
        'Thomas',
        'Georgianna',
        'Leigha',
        'Alejandro',
        'Marquis',
        'Joan',
        'Stephania',
        'Elroy',
        'Zonia',
        'Buffy',
        'Sharie',
        'Blythe',
        'Gaylene',
        'Elida',
        'Randy',
        'Margarete',
        'Margarett',
        'Dion',
        'Tomi',
        'Arden',
        'Clora',
        'Laine',
        'Becki',
        'Margherita',
        'Bong',
        'Jeanice',
        'Qiana',
        'Lawanda',
        'Rebecka',
        'Maribel',
        'Tami',
        'Yuri',
        'Michele',
        'Rubi',
        'Larisa',
        'Lloyd',
        'Tyisha',
        'Samatha',
    );

    $lastname = array(
        'Mischke',
        'Serna',
        'Pingree',
        'Mcnaught',
        'Pepper',
        'Schildgen',
        'Mongold',
        'Wrona',
        'Geddes',
        'Lanz',
        'Fetzer',
        'Schroeder',
        'Block',
        'Mayoral',
        'Fleishman',
        'Roberie',
        'Latson',
        'Lupo',
        'Motsinger',
        'Drews',
        'Coby',
        'Redner',
        'Culton',
        'Howe',
        'Stoval',
        'Michaud',
        'Mote',
        'Menjivar',
        'Wiers',
        'Paris',
        'Grisby',
        'Noren',
        'Damron',
        'Kazmierczak',
        'Haslett',
        'Guillemette',
        'Buresh',
        'Center',
        'Kucera',
        'Catt',
        'Badon',
        'Grumbles',
        'Antes',
        'Byron',
        'Volkman',
        'Klemp',
        'Pekar',
        'Pecora',
        'Schewe',
        'Ramage',
    );

    $name = $firstname[rand ( 0 , count($firstname) -1)];
    $name .= ' ';
    $name .= $lastname[rand ( 0 , count($lastname) -1)];

    return $name;
}

**Comment by stefanak-michal** [comment]
I was testing your problem but I was not able to replicate it. You mentioned you have this library version 2.8.8 but this version doesn't exists.

I was testing with latest version of this library and neo4j aura (it's already v5) and with local neo4j 4.4.12 and local neo4j 5.1.0. Works okay on all of them.

**Comment by Alaizabel** [comment]
Hi Michal, you were right, I misread the package number. Correct version is 2.7.0. I also tested now with a local Neo4J Instance 4.4.14 to make sure if have no remot eproblem but I still receive this strange behavior. The inner loop stops with the first record, when I put a COUNT before the inner loop it spills out all 11 names. I have really no clue what this can be. Woud you lke to have a teamviewer session to see this behavior - I could go step by step and show you what I do? Maybe you spot something where I have a mistake.

**Comment by stefanak-michal** [comment]
You are right, on version 2.7.0 it does happen. But as you can see there is already tag 2.8.0 (not release yet) and it works with it correctly. That means it was fixed already, but not published as release. Propably @transistive wants to add something else into it.

https://github.com/neo4j-php/neo4j-php-client/compare/2.7.0...2.8.0

_Also I don't know how you whole code looks like but you should avoid queries in loop, if you can query everything before._
```php
$outerLoopQuery = "MATCH (n) RETURN n.Name as Name, n.Nummer AS Nummer";
$outerLoopResult = $client->run($outerLoopQuery);
foreach ($outerLoopResult as $recordsOuterLoop) {
	echo $recordsOuterLoop['Name'] . '<br>';
}
```

**Comment by transistive** [comment]
Hello everyone! I just simply forgot to release it on github. It is already available on packagist!

2.8.0 and 2.8.1 will be released later today as well on GitHub

**Comment by Alaizabel** [comment]
Hi,

I updated the package and re-testet - works like a charme now, thank you!

Am 20.11.2022 um 13:23 schrieb Ghlen Nagels:
