### ISSUE TITLE
[No write operations are allowed]: Wrong node is selected in cluster with multiple databases

### ISSUE THREAD

**Issue by GinoPane** [neo4j-php/neo4j-php-client#158]
Hi!

We found an issue with connection pool which selects wrong node when we have multiple databases in the cluster.

Here's how our databases are distributed between nodes, hopefully the image is not too small:

![image](https://user-images.githubusercontent.com/3897579/207903381-3ef04d7e-eb60-4b02-9a78-320728817127.png)

DEV db leader is on node 1 and STAGING|UAT dealers are on nodes 0|2 respectively.

And here's the problem: when we use DEV db, writes are fine. But when we use either staging or uat, connection pool selects node 1 for writes (basically, it takes the leader of dev db) and therefore we have an error:

`Neo4j errors         
         detected. First one with code "Neo.ClientError.Cluster.NotALeader" and message "No write operations are allowed
         directly on this database. Writes must pass through the leader. The role of this server is: FOLLOWER" `

The reason of this is because database is null when the config is passed into this method:
![image](https://user-images.githubusercontent.com/3897579/207904546-96eda6d5-bef5-4ba9-b044-1ffa0d2c9cbb.png)

And it happens, because the method "acquire" is being called several times, and at first it is being called with a default session config (with null database). When it is called with default config, the cache is being set and driver thinks that the routing table is initialised.

![image](https://user-images.githubusercontent.com/3897579/207904839-290ab6e9-a573-4f84-a4b9-8204c7c0c1e1.png)

### Fix

The fix for this seems to be pretty straightforward if we just concat the cache key with database name. In that case the routing table will be refreshed for a correct database and the node will be selected correctly:

![image](https://user-images.githubusercontent.com/3897579/207905540-8d8d6059-17e3-4de1-9f93-d5621061dd12.png)
 
@transistive does it make sense? Could you please make this fix or you'd like to investigate more?

**Comment by transistive** [comment]
Hi @GinoPane,

Thank you so much for the detailed write-up and analysis!

It makes a lot of sense. Maybe you can add the config to the create Key method, so it gets used everywhere?

Feel free to send in a PR. I can do it tomorrow otherwise.

Kind regards,

Ghlen

**Comment by GinoPane** [comment]
@transistive done. 

Though the fix works I have doubts. I didn't dig deep, but why "acquire" is called several times with no config? Or better to say, it is being called with config, but it is a default config with no database set. Even if we do "withDefaultSessionConfig" on client build.

Maybe a better fix would be to call it with a relevant config only?

**Comment by transistive** [comment]
Thank you @GinoPane,

It seems you have found another bug then as well! It should always use the configured default session config. I'll ook into this later today. I am currently preparing another presentation.

I am extremely grateful for this!
