### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by tomswinkels** [neo4j-php/neo4j-php-client#163]
We're running the client now on PHP 8.2 but there we are getting warnings.

`Return type of Laudis\Neo4j\Enum\AccessMode::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laudis/neo4j-php-client/src/Enum/AccessMode.php on line 44`

Are there plans to support PHP 8.2?

**Comment by transistive** [comment]
Hello @tomswinkels ,

Can you confirm you are on the latest version of the client? This error was already introduced in PHP version 8.0 and was fixed by adding the required attributes in later versions.

Kind regards,

Ghlen

**Comment by tomswinkels** [comment]
Hi @transistive,

We use the latest version?

`"name": "laudis/neo4j-php-client",
"version": "2.8.2",`

**Comment by transistive** [comment]
Interesting! It looks like it is an issue with a small personal project of mine for typed enumerations. I'll update it downstream today and ping you once it is done!

Thank you for bringing this to my attention

**Comment by transistive** [comment]
Besides that, it appears the archaic way of me trying to solve the problem over a year ago is suboptimal. I've pushed it onto main and let the tests do their thing. 2.8.3 will be out later tonight.

**Comment by transistive** [comment]
I released 2.8.3, can you confirm it works on your end?

Kind regards,

Ghlen

**Comment by tomswinkels** [comment]
@transistive thnx that error is fixed, there is one error left now.

`Return type of Laudis\Neo4j\Types\AbstractCypherObject::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laudis/neo4j-php-client/src/Types/AbstractCypherObject.php on line 73`

**Comment by tomswinkels** [comment]
Any update?

**Comment by transistive** [comment]
I am currently working on version 3, which should be released by tonight.

**Comment by transistive** [comment]
I've tagged version 3.0.0 and it is available on packagist.
It is already late here so I will circle back to this tomorrow for the release notes.
