### ISSUE TITLE
Incompatibility with Laravel 9.48

### ISSUE THREAD

**Issue by infureal** [neo4j-php/neo4j-php-client#166]
**Describe the bug**
Cannot install in fresh laravel 9.48 project. Package `psr/simple-cache:^1.0` incompatible with `psr/simple-cache:^3.0` 

https://github.com/neo4j-php/neo4j-php-client/blob/2.8.3/composer.json#L36

**To Reproduce**
1. `composer create-project laravel/laravel <name> "9.48.*"`
2. `composer require laudis/neo4j-php-client`

**Logs in created project**

```
$ composer show laravel/framework

name     : laravel/framework
descrip. : The Laravel Framework.
keywords : framework, laravel
versions : * v9.48.0
type     : library
```

```
$ composer show psr/simple-cache

name     : psr/simple-cache
descrip. : Common interfaces for simple caching
keywords : cache, caching, psr, psr-16, simple-cache
versions : * 3.0.0
type     : library
```

**Comment by transistive** [comment]
Thanks for the heads up! I have reduced the minimum version. It will be fixed in version 3.0.1
