### ISSUE TITLE
"Laudis\Neo4j\Types\AbstractCypherSequence::getGenerator(): Return value must be of type Iterator, null returned"

### ISSUE THREAD

**Issue by tomswinkels** [neo4j-php/neo4j-php-client#175]
After update to version 2.8.3 we get some error:

```
"Laudis\Neo4j\Types\AbstractCypherSequence::getGenerator(): Return value must be of type Iterator, null returned"

/code/vendor/laudis/neo4j-php-client/src/Types/AbstractCypherSequence.php:440
/code/vendor/laudis/neo4j-php-client/src/Types/AbstractCypherSequence.php:381
```

**Comment by transistive** [comment]
Hello @tomswinkels,

I have added a test that returns an empty array, and it works without any problems.

Can you provide a reproducible example, so I can check it out?

Thank you

**Comment by tim-hanssen** [comment]
I just found out that the problem was caused by a mix-up of version 2.3 and 2.8 due to caching. So case closed!
