### ISSUE TITLE
TCP connections do not close in the new version

### ISSUE THREAD

**Issue by tomswinkels** [neo4j-php/neo4j-php-client#178]
**Describe the bug**
After we migrate the library from 2.8.3 to 2.3.9 we have problems that the connections are not closing any more.

Now we are back to the 2.8.3 version and there are no problems.

**Desktop:**
 - Library version: 2.3.9
 - Neo4j Version: 3.5.35
 - PHP version: 8.2.5-fpm
 - OS: Linux

**Comment by transistive** [comment]
Hi @tomswinkels,

Thank you for reaching out. What connections aren't closing? On the Neo4j server side?

Is there any way you can provide us with a reproducible code example?

Kind regards,

Ghlen

**Comment by tomswinkels** [comment]
Hi @transistive,

Difficult to a reproduction example.

In Neo4j, there are no open queries.

On the load balancer, we see above 500 open TCP connections to Neo4j.

 After that, we get some errors from Neo4j that all the slots are full.

**Comment by transistive** [comment]
Hey Tom, did you manage to try version 3 already? It may be gone there. It's proving difficult to reproduce on my end.

**Comment by transistive** [comment]
Feel free to reopen if this is not the case
