### ISSUE TITLE
Fatal Error encountered due to return type incompatibility of implementing class function

### ISSUE THREAD

**Issue by dataskills** [neo4j-php/neo4j-php-client#182]
**Describe the bug**
 Return type of `Laudis\Neo4j\Types\AbstractCypherObject::offsetGet($offset)` should either be compatible with `ArrayAccess::offsetGet(mixed $offset): mixed`, or the `#[\ReturnTypeWillChange] ` attribute should be used to temporarily suppress the notice

**To Reproduce**
1. Create client with neo4j scheme 
2. Run a simple cypher query , i.e `$client->run("CREATE (n:Person {name: 'Bob'}) RETURN id(n)");`
3. See error

**Expected behavior**
No error occurrence

**Screenshots**

 - Library version: 2.8.0
 - Neo4j Version: 4.4.0
 - PHP version: 8.1.13
 - OS: MacOS Ventura 13.3.1

**Additional context**
Adding the #[\ReturnTypeWillChange] successfully supresses the error

**Comment by transistive** [comment]
Hello @dataskills,

Thank you for posting this issue.

Can you please update to the latest version to confirm the issue persists?

It should be solved in later releases.

Thanks!

Ghlen

**Comment by dataskills** [comment]
Forgive me if I am missing something but I thought 2.8.0 was the latest version.

**Comment by dataskills** [comment]
Sorry, I see 2.8.1, I will try it

**Comment by dataskills** [comment]
To clarify, 2.8.0 is the latest release which has the error, but the error is fixed at tag 2.8.1. I tried to check out the tag at 2.8.3 just to compare and I figured out that the error is present in 2.8.3 but, again,  is not present in 2.8.1. I think I found the cause, consider the change in `src/Types/AbstractCypherObject.php` in this particular diff: https://github.com/neo4j-php/neo4j-php-client/compare/2.8.1...2.8.3

I am not sure what the release roadmap is, and I know you must be busy but let us know if you can how you plan to proceed if you can. Have a great weekend, Cheers.

**Comment by transistive** [comment]
Hello @dataskills, it should be fixed in version 3.0.4 Feel free to reopen if this is not the case.
