### ISSUE TITLE
abandonned http-factory

### ISSUE THREAD

**Issue by spham** [neo4j-php/neo4j-php-client#183]
Hi,
Can we be confident when receiving this type of message during installation?

`Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.`

**Comment by transistive** [comment]
Hi @spham!

Thank you for bringing this to my attention. In theory it should be fine for now.

I'll make sure to update the downstream dependencies Wednessday.

Kind regards,

Ghlen

**Comment by transistive** [comment]
Fixed in dev-main. It will be released in 3.0.5 later today
