### ISSUE TITLE
Path only returns Unbound Relationships

### ISSUE THREAD

**Issue by in3rsha** [neo4j-php/neo4j-php-client#205]
I'm new to using this tool so forgive me if I'm using it incorrectly.

I'm retrieving a path from Neo4j using this style of query:

```
MATCH (start :node {property:'x'})
MATCH (end :node {property:'y'})
MATCH path=shortestPath((start)-[:a|b*1..100]-(end))
RETURN path
```

However, when I try to work with the results using  something like:

```
foreach ($results as $result) {
  // Returns path
  $path = $result->get('path');

  // Nodes
  $nodes = $path->getNodes();

  // Relationships
  $relationships = $path->getRelationships();
}
```

It appears all of the `$relationships`  are of the type `UnboundRelationship`, so they do not have the `$startNodeId` or `$endNodeId` that a `Relationship` has.

Is there any way to return the data from this query with relationships that indicate which nodes they are pointing to?

So far I've just been running through the `$nodes` and `$relationships` arrays individually and trying to connect them together.

**Comment by stefanak-michal** [comment]
Hi. It is not a bug. Check here to learn more https://www.neo4j.com/docs/bolt/current/bolt/structure-semantics/#structure-path

**Comment by stefanak-michal** [comment]
No problem, glad to help.
