### ISSUE TITLE
Crash on property with value "\\"

### ISSUE THREAD

**Issue by tomswinkels** [neo4j-php/neo4j-php-client#232]
When some of the properties had a value with \\ than the client crashed.

**Comment by exaby73** [comment]
Hey @tomswinkels. Thanks for raising this. Can you elaborate on your issue? What sort of logs are you seeing? Can you provide some information about your Neo4J version as well so that I can try to recreate your issue?

**Comment by exaby73** [comment]
Thanks for the info @tim-hanssen and @tomswinkels. I can confirm that I can reproduce this issue. I'm working on a fix and I'll get back to you soon :)

**Comment by exaby73** [comment]
Hey. This should be fixed and released in 3.1.3. Please let us know if you have any other issues :)

**Comment by tim-hanssen** [comment]
Thx! Issue is fixed! 🥇
