### ISSUE TITLE
An issue with the BOLT protocol

### ISSUE THREAD

**Issue by jac12498** [neo4j-php/neo4j-php-client#34]
This may be a problem with the bolt driver, but I thought that I would mention it here as well.

My project involves finding the election districts that contain a specific geolocation. Each of District node has one or more related Border nodes. The Border nodes contain the geolocation of the points that define its border - i.e. a polygon and a bounding box defined by 2 points (min and max) of the polygon. I am basically then attempting to find which polygons contain the specific geolocation.

I do this in 2 steps. The first step is to determine which nodes could contain the point by checking to see if the point is in the bounding box. This is the following simple query:

      MATCH (b:Border) WHERE b.min < point({latitude: $lat, longitude: $long}) < b.max RETURN b;

When executed through the Neo4j Browser, the result (8 Borders in my test case) returns and displays in 21 ms. When executed through the BOLT protocol of the PHP driver, the error below is returned. With the HTTP protocol it works.

PHP Fatal error:  Uncaught Bolt\error\UnpackException: Structure call for method "unpackFloat" generated unpack error in /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php:194
Stack trace:
#0 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(170): Bolt\PackStream\v1\Unpacker->unpackSpecificStructure()
#1 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(103): Bolt\PackStream\v1\Unpacker->unpackStruct()
#2 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(328): Bolt\PackStream\v1\Unpacker->u()
#3 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(126): Bolt\PackStream\v1\Unpacker->unpackList()
#4 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(222): Bolt\PackStream\v1\Unpacker->u()
#5 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(192): Bolt\PackStream\v1\Unpacker->unpackMap()
#6 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(170): Bolt\PackStream\v1\Unpacker->unpackSpecificStructure()
#7 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(103): Bolt\PackStream\v1\Unpacker->unpackStruct()
#8 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(328): Bolt\PackStream\v1\Unpacker->u()
#9 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(126): Bolt\PackStream\v1\Unpacker->unpackList()
#10 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(79): Bolt\PackStream\v1\Unpacker->u()
#11 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/protocol/AProtocol.php(103): Bolt\PackStream\v1\Unpacker->unpack()
#12 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/protocol/V4.php(39): Bolt\protocol\AProtocol->read()
#13 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/protocol/V4.php(25): Bolt\protocol\V4->pull()
#14 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/Bolt.php(274): Bolt\protocol\V4->pullAll()
#15 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php(130): Bolt\Bolt->pullAll()
#16 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php(57): Laudis\Neo4j\Network\Bolt\BoltSession->runStatements()
#17 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Client.php(54): Laudis\Neo4j\Network\Bolt\BoltSession->run()
#18 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Client.php(46): Laudis\Neo4j\Client->runStatements()
#19 /home/mydistrict/public_html/neo4j/v0.1/Application/Models/Neo4jBase.php(336): Laudis\Neo4j\Client->runStatement()
#20 /home/mydistrict/public_html/neo4j/v0.1/Application/Models/District.php(116): Model\Neo4jBase->queryMultiple()
#21 /home/mydistrict/public_html/neo4j/v0.1/tests/district_geolocation.php(22): Model\District->getByGeoLocation()
#22 {main}

Next Laudis\Neo4j\Exception\Neo4jException: Neo4j errors detected. First one with code "" and message "Structure call for method "unpackFloat" generated unpack error" in /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php:132
Stack trace:
#0 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php(57): Laudis\Neo4j\Network\Bolt\BoltSession->runStatements()
#1 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Client.php(54): Laudis\Neo4j\Network\Bolt\BoltSession->run()
#2 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Client.php(46): Laudis\Neo4j\Client->runStatements()
#3 /home/mydistrict/public_html/neo4j/v0.1/Application/Models/Neo4jBase.php(336): Laudis\Neo4j\Client->runStatement()
#4 /home/mydistrict/public_html/neo4j/v0.1/Application/Models/District.php(116): Model\Neo4jBase->queryMultiple()
#5 /home/mydistrict/public_html/neo4j/v0.1/tests/district_geolocation.php(22): Model\District->getByGeoLocation()
#6 {main}
  thrown in /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php on line 132

**Comment by transistive** [comment]
Thank you for taking the time to post this issue.

I am also subscribed to the bolt driver. If no one picks up the issue by the weekend, I will create a PR there. Thanks for the good work!

Kind regards,

Ghlen

**Comment by transistive** [comment]
This issue has been closed because of inactivity.
