### ISSUE TITLE
Feature Request: OGM Formatter

### ISSUE THREAD

**Issue by transistive** [neo4j-php/neo4j-php-client#37]
One of the essential features the driver needs is an Object Graph Mapper.

At the moment, all results are encapsulated in arrays, maps and vectors, but there should be a typing system available.

Examples of this can be found here: https://neo4j.com/docs/driver-manual/current/cypher-workflow/#driver-type-mapping

**Comment by Teglgaard** [comment]
@Mulkave Awesome that you want to take on this task! Kudos for that since it is a difficult task!

**Comment by Mulkave** [comment]
> Awesome that you want to take on this task! Kudos for that since it is a difficult task!
@Teglgaard it's a pleasure 😄

**Comment by transistive** [comment]
Closed and merged in branch v2.0 :partying_face: 

Relevant PR: #36
