### ISSUE TITLE
how to work with neo4j database in php

### ISSUE THREAD

**Issue by nkem56** [neo4j-php/neo4j-php-client#47]
I have successfully install the projects via composer and have my neo4j database server running locally.
I have also tested the sample applications 

**sample.php** 
```

<?php



require ('vendor/autoload.php');
$client = Laudis\Neo4j\ClientBuilder::create()
    ->addHttpConnection('backup', 'http://neo4j:foodisgood56@localhost')
    ->addBoltConnection('default', 'bolt://neo4j:foodisgood56@localhost')
    ->setDefaultConnection('default')
    ->build();




foreach ($client->run('UNWIND range(1, 9) as x RETURN x') as $item) {
    echo $item->get('x');
}


?>

```

and it echos  **123456789** which suggests that my local neo4j database server is working fine. working fine

**Here are my questions**

Please do you have sample of 

**1.) How create table Eg Table users_table via neo4js in php**

something like
`
create table users_table(id int primary key auto_increment, fullname varchar(30), password varchar(30), email varchar(30));

`

**2.) How to inserts, updates, select and delete example via php for neo4js**

How can I achieve equivalents of this php PDO in Neo4j Database

**For insert** 

```

$statement = $db->prepare('INSERT INTO users_table
(password,fullname,email)
 values
(:password,:fullname,:email)');

$statement->execute(array( 
':password' => 'my pass',
':fullname' => 'Nkem C',
':email' => 'testing@gmail.com'));
```

**For Update**
```

$update = $db->prepare('UPDATE users_table set password=:password, fullname=:fullname where email=:email');

$update->execute(array( 
':password' => 'my pass1',
':fullname' => 'Nkem C1',
':email' => 'testing@gmail.com'));
```

**For Delete**

```

$del1 = $db->prepare('DELETE from users_table  where email=:email');

$del1->execute(array( 
':email' => 'testing@gmail.com'));



// delete all
$del2 = $db->prepare('DELETE from users_table');
$del2->execute(array());

```

**For Select**

```

$query1 = $db->prepare('SELECT * from users_table  where email=:email and password=:password');

$query1->execute(array( 
':email' => 'testing@gmail.com',
':password' => 'my pass'
));



// select all
$query2 = $db->prepare('SELECT * from users_table');
$query2->execute(array());
```

Thanks

**Comment by transistive** [comment]
Hello nkem56,

Thank you for your questions. I am afraid the scope of this question is too broad to answer here. The questions you ask imply you do not have a solid grasp of how neo4j works instead of the driver. I therefore advise you to go through this:
https://neo4j.com/developer/cypher/guide-sql-to-cypher/

Hope this helps!

Kind regards,
Ghlen

**Comment by nkem56** [comment]
resolved

**Comment by transistive** [comment]
No problem @nkem56, I am glad to be of help :+1: Good luck on your graph database ventures!

**Comment by nkem56** [comment]
Thanks
