### ISSUE TITLE
 iterate through a list of map records or an array to get required values in neo4j Database

### ISSUE THREAD

**Issue by nkem56** [neo4j-php/neo4j-php-client#48]
Am working with neo4j database via this projects

**My Code**
```

<?php

$query = $client->run('MATCH (n:Dept1) RETURN n LIMIT 25');
print_r($query );

/*
echo $json = json_decode($query, true);
foreach($json as $v1){

echo $v1['location'];
echo $v1['dname'];
echo $v1['deptno'];

}
*/

?>
```

**when print a records in the array, i have the following output/records.**

`
Ds\Vector Object ( [0] => Ds\Map Object ( [0] => Ds\Pair Object ( [key] => n [value] => Array ( [location] => Hyderabad [dname] => Accounting [deptno] => 10 ) ) ) [1] => Ds\Map Object ( [0] => Ds\Pair Object ( [key] => n [value] => Array ( [location] => Hyderabad1 [dname] => Accounting1 [deptno] => 11 ) ) ) [2] => Ds\Map Object ( [0] => Ds\Pair Object ( [key] => n [value] => Array ( [location] => Hyderabad2 [dname] => Accounting2 [deptno] => 12 ) ) ) )
`

Please how, can I iterate through the array and display values for **location, dname and deptno**

Thanks

**Comment by transistive** [comment]
Hello nkem56,

The results are in two containers: a `\Ds\Vector` and a `\Ds\Map`. You can iterate like this:

```php
foreach ($query as $row) {
    $depth = $row['n'];
    echo $depth['location'];
    echo $depth['dname'];
    echo $depth['deptno'];
}
```

You cannot immediately access location, dname and deptno as you return a node and not its attributes. You must first access the node like this: `$depth = row['n']` before you can access its properties.

Hope this helps!

Kind regards,
Ghlen

**Comment by transistive** [comment]
This issue is closed due to inactivity
