### ISSUE TITLE
Reformat result after run

### ISSUE THREAD

**Issue by tim-hanssen** [neo4j-php/neo4j-php-client#60]
Hi all,

I have a question, all our queries are handled by the default OGMFormatter. Which is great in almost all situations.
But we have one case where we have to put the whole result into our own local formatter, and that formatter needs an array.

Is there any way I can "reformat"? :) Feeding the result from the OGMFormatter to the BasicFormatter to get it back as arrays?

**Comment by transistive** [comment]
Hello Tim,

You cannot feed the results from the OGMFormatter to the BasicFormatter as they need the original results produced from the HTTP or bolt protocol.

I created an example of how a custom combined format might look. Feel free to use this as a template and build from there.

Good luck!

https://gist.github.com/transistive/90ef59c2b02dc9967d82e4ab3d8bf435

**Comment by transistive** [comment]
Also, note I did not include psalm typing in this example as I wanted to keep it barebones. If you need help with that I can include it as well :+1:

**Comment by transistive** [comment]
Closed due to inactivity
