### ISSUE TITLE
HttpOGMArrayTranslator.php causes infinite loop

### ISSUE THREAD

**Issue by m-kroell** [neo4j-php/neo4j-php-client#65]
Hi, 

i kept getting this error after switching from the old graphaware neo4j client to this one:
Maximum function nesting level of '500' reached, aborting!

I've tracked it down to line 84 in HttpOGMArrayTranslator.php:
`$tbr->push($this->translateContainer($value));`

i think $value should be $x, as this fixed it for me
`$tbr->push($this->translateContainer($x));`

**Comment by transistive** [comment]
Hello @m-kroell,

Thank you for fixing the issue yourself! I have implemented your solution and it works wonders.

The release for version 2.0.8 will be Monday. In the meantime, you can use the bugfix when picking `dev-main`.

Kind regards,

Ghlen
