### ISSUE TITLE
Requested Protocol version (80.84.84.72) not yet implemented

### ISSUE THREAD

**Issue by milanchheda-cactus** [neo4j-php/neo4j-php-client#67]
Hi there,

First of all, thanks for the excellent package.

Here is my code:
```
$client = ClientBuilder::create()
    ->withFormatter(new BasicFormatter())
    ->withDriver('neo4j', 'neo4j+s://bolt.db.xxxxxxxxx.xx:7687', Authenticate::basic('neo4j', 'xxxxxxxxxxxxxx'))
    ->build();
```

But I keep getting following error:
`Requested Protocol version (80.84.84.72) not yet implemented`

Any help/inputs would be much appreciated.

Thanks.

**Comment by transistive** [comment]
Hello @milanchheda-cactus,

Thank you for posting this issue. Can you send me your php, client and neo4j version? That way I can try and reproduce the issue.

Thank you,

Ghlen

**Comment by milanchheda-cactus** [comment]
Sorry for the late response.

Do you mean you want the actual string for this `neo4j+s://bolt.db.xxxxxxxxx.xx:7687` instead of `xxxxxxxxx`?

**Additional info:**
PHP: 8.0.6
Laravel: 8.51.0
"laudis/neo4j-php-client": "^2.0",

**Comment by transistive** [comment]
No problem @milanchheda-cactus,

You can find the client version by running: `composer show -i laudis/neo4j-php-client`.

By neo4j version mean I mean the version of the actual database (eg 4.3.0).

Thanks!

**Comment by milanchheda-cactus** [comment]
Hey @transistive ,

I checked and neo4j is version 4.2.6

Thanks.

**Comment by transistive** [comment]
Hello @milanchheda-cactus,

The only thing I can think of right now is an issue with DNS within neo4j or a bug with SSL. It might be easiest if you could provide me access to the database, so I can reproduce the problem locally. 

If you are comfortable with it, you can send me the info at `ghlen@pm.me`. If not, I will have to try and set up my own hosting with SSL certificates and try to reproduce it, which will take a long time and might not even be guaranteed to work.

Is that all right with you?

Kind regards,
Ghlen

**Comment by milanchheda-cactus** [comment]
Hey @transistive ,

Let me check this internally and get back to you.

Thanks,
Milan

**Comment by milanchheda-cactus** [comment]
Hey @transistive,

I checked internally and team is looking into it. Hopefully, this will be resolved internally, if not, I will re-open and comment it here. 

Thanks,
Milan

**Comment by milanchheda-cactus** [comment]
Hey @joseraul ,

I don't recollect completely but it was an internal network issue. Also, I had ended up with `->withDriver("http"` as `neo4j+s` didn't work out for me.

Thanks.
