### ISSUE TITLE
error message : Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by cqkd6381** [neo4j-php/neo4j-php-client#89]
**Describe the bug**
When running the following code, the error is as follows

**Code**

> $result = $this->client->writeTransaction(static function (TransactionInterface $tsx) {
            $result = $tsx->run('MERGE (x {y: "z"}:X) return x');
            return $result->first()->get('x')['y'];
    });

**Screenshots**
![image](https://user-images.githubusercontent.com/16833623/139040835-d6f7e972-fd19-4b54-b9fb-640e95eb3403.png)

**Desktop (please complete the following information):**
 - Library version: 2.2.1
 - Neo4j Version: 4.3.6
 - PHP version: 7.4.14
 - OS: Linux

**Comment by transistive** [comment]
Very interesting! Your query is wrong; the error I receive on the driver is this: 
```
Laudis\Neo4j\Exception\Neo4jException : Neo4j errors detected. First one with code "Neo.ClientError.Statement.SyntaxError" and message "Invalid input ':': expected ")" (line 1, column 18 (offset: 17))
"MERGE (x {y: "z"}:X) return x"
                  ^ (Neo.ClientError.Statement.SyntaxError)"
```

I cannot reproduce the cryptic error message you received. Can you tell me how you built the client and what HTTP client you are using?

Thank you.

**Comment by transistive** [comment]
Closed due to inactivity
