### ISSUE TITLE
Can't connect to Neo4j Aura - Free Tier

### ISSUE THREAD

**Issue by mahruqs** [neo4j-php/neo4j-php-client#95]
I am unable to connect to my Aura DB - which is current without any content.

I am using the neo4j-php-client library. Here is the test code I have, which uses the blog posts for the client library. I used composer to download the neo4j php client library yesterday.

```
$client = ClientBuilder::create()
                 ->withDriver(
                        'neo4j', 
                        'neo4j+ssc://1345dc4c.databases.neo4j.io', 
                        Authenticate::basic('neo4j', 'password'),
                        (30*1000))
                ->withDefaultDriver('neo4j')
                ->build();

                $statement = new Statement('CREATE (user {email: $email})', ['email' => 'abc@hotmail.com']);
                $client->runStatement($statement);
```

Here is the error I am getting:

Bolt\error\ConnectException
Read error
VENDORPATH/stefanak-michal/bolt/src/connection/StreamSocket.php at line 106

I've attached a PDF of the full backtrace.
[Bolt_error_ConnectException.pdf](https://github.com/neo4j-php/neo4j-php-client/files/7776096/Bolt_error_ConnectException.pdf)

**Comment by transistive** [comment]
Hello Mahruqs!

Thank you for creating this issue. You have set up the connection to expect a self-signed certificate (ssc), Can you confirm the issue persists if you tell the driver to expect a signed certificate?

You do this by changing the uri from `neo4j+ssc://1345dc4c.databases.neo4j.io` to `neo4j+s://1345dc4c.databases.neo4j.io`.

Looking forward to your feedback,

\- Ghlen

**Comment by transistive** [comment]
It appears neo4j there was a small bug when configuring the driver to use self-signed certificates. Thank you for posting the issue. It will be fixed in version 2.3.4. In the meantime, version 2.3.3 will also work with +s instead of +ssc

**Comment by mahruqs** [comment]
Hi Ghlen, Apologies for the late reply -- I was traveling yesterday. I tried with just the neo4j+s uri, and am getting another error (I had tried that earlier as well). I had tried just neo4j+s before adding the "ssc" before testing with ssc and was still unsuccessful.

stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
VENDORPATH/stefanak-michal/bolt/src/connection/StreamSocket.php at line 64

57         }
58 
59         if (!stream_set_blocking($this->stream, true)) {
60             throw new ConnectException('Cannot set socket into blocking mode');
61         }
62 
63         if (!empty($this->sslContextOptions)) {
64             if (stream_socket_enable_crypto($this->stream, true, STREAM_CRYPTO_METHOD_ANY_CLIENT) !== true) {
65                 throw new ConnectException('Enable encryption error');
66             }
67         }
68 
69         $timeout = (int) floor($this->timeout);
70         if (!stream_set_timeout($this->stream, $timeout, (int) floor(($this->timeout - $timeout) * 1000000))) {
71             throw new ConnectException('Cannot set timeout on stream');

I've attached the error trace as PDF.
[SSLCertificateError-neo4j.pdf](https://github.com/neo4j-php/neo4j-php-client/files/7780600/SSLCertificateError-neo4j.pdf)

**Comment by mahruqs** [comment]
@transistive , no sure if you got a chance to see the error I got above, or if you have any additional guidance. Thank you!

**Comment by transistive** [comment]
I lost track of it as the issue was already closed. I will take a look at it now!

**Comment by transistive** [comment]
Sadly, I am not able to reproduce the error. I get the message the address is unavailable. Is the aura instance temporarily disabled by any chance?

Everything works when using my own aura instance

**Comment by mahruqs** [comment]
I'm so sorry. It was paused for some reason. I'm still getting the same error. I'd be happy to send you the connection info via email if that is okay -- I just got the latest code from github, and am still getting the same error.

stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed 

Here is my code:

$client = ClientBuilder::create()
                 ->withDriver(
                        "neo4j", 
                        "neo4j+s://1345dc4c.databases.neo4j.io", 
                        Authenticate::basic("neo4j", "KZ2jKFhH-k3waoRPrFnewER34tr7gpQ_hbyveZz1rr0"),
                        (30*1000))
                ->withDefaultDriver('neo4j')
                ->build();

               $statement = new Statement('CREATE (user {email: $email})', ['email' => 'abc@hotmail.com']);
               $client->runStatement($statement);

**Comment by mahruqs** [comment]
Sorry about pasting the password in code. My bad. 

I tried this from one of the other threads, and did not get the OpenSSL error: [https://github.com/neo4j-php/neo4j-php-client/issues/24#issuecomment-765593383].

Is there a way ot add "verify_peer" and "allow_self_Signed" flags into the ClientBuilder:create call?

`
$url = "1345dc4c.databases.neo4j.io";
            $conn = new \Bolt\connection\StreamSocket($url, 7687);
            $conn->setSslContextOptions([
                "verify_peer" => false,
                "allow_self_signed" => true,
            ]);

            $bolt = new \Bolt\Bolt($conn);
        

           $bolt->init("Test", "neo4j", "<password>");

            // Execute query
            $res = $bolt->run("RETURN 1 AS num, 2 AS cnt");
            // Pull records from last query
            $rows = $bolt->pull();
            
            var_dump($res);
            var_dump($rows);

`

Result:

res:
array ( 't_first' => 7, 'fields' => array ( 0 => 'num', 1 => 'cnt', ), )
rows:
array ( 0 => array ( 0 => 1, 1 => 2, ), 1 => array ( 'bookmark' => 'f4c803c1-e67c-4473-ab28-0e01ab41c28e:3', 'type' => 'r', 't_last' => 0, 'db' => 'neo4j', ), )

**Comment by transistive** [comment]
Hello @mahruqs,

It appears we keep missing each other by a few days! I still get the error: `php_network_getaddresses: getaddrinfo failed: Name or service not known`, is the instance offline again?

It is not possible to immediately change the SSL settings. I am on the fence about allowing this option. But I first want to be able to reproduce it. I have tested it with multiple instances of Aura and have never had this error.

The moment I receive a new instance from you, I will prioritise it because the issue appears very persistent.

Kind regards,

Ghlen

**Comment by mahruqs** [comment]
I'm so sorry @transistive . My instance keeps going down since it's the free tier. I'll try to keep an eye on it when i'm online. 

![image](https://user-images.githubusercontent.com/6256573/148710526-65088e3b-25af-423e-a7f4-a3a2dd865095.png)

**Comment by transistive** [comment]
Ok, I tested it without any problems on version 2.3.3:

![image](https://user-images.githubusercontent.com/16435930/148738484-299d3714-954e-4758-9cc4-1f3bf1ce0dd8.png)

Would you mind scheduling a call with me, so I can look at the crash from your end? If this is a bug, I need to be able to reproduce it.

Please email me at ghlen@pm.me with your availabilities if you want to schedule a call.

Thank you for your patience,

Ghle

**Comment by transistive** [comment]
Hello @mahruqs,

Thank you for the very insightful call. I am asking around internally in Neo4j if they have any experience with the problem. If it appears to be unsolvable, I will make sure there is an option to turn off SSL verification manually.

I am grateful for your patience!

**Comment by transistive** [comment]
Hello @mahruqs,


Can you confirm you are using windows 10? There appears to be a possible issue there. I will try and reproduce it in a vm.
Can you also ask a colleague in the US if he/she also receives the error? This way we might be able to rule it networking issues.
In the meantime, I will put together a solution to turn off SSL peer verification. But beware, this massively decreases security.

Kind regards,

Ghlen

**Comment by transistive** [comment]
Hello again @mahruqs ,

Sorry to keep spamming you, but I also cannot reproduce the error on a windows 10 VM. So the most likely options might be a botched openSSL install, a networking issue, or a difference between a VM and a normal installation of windows 10.

I will update the SSL options later today.

Kind regards,

Ghlen

**Comment by transistive** [comment]
In version 2.3.8 you can now override the SSL behaviour. Can you confirm something like this works?

```php
$config = DriverConfiguration::default()
            ->withSslConfiguration(
                SslConfiguration::default()
                    ->withVerifyPeer(false) //disables peer verification
                    ->withMode(SslMode::FROM_URL()) // looks at the URL to determine the enabling of ssl
            );
            
$driver = \Laudis\Neo4j\Basic\Driver::create('neo4j+s://localhost', $config);

$client = \Laudis\Neo4j\ClientBuilder::create()
            ->withDefaultDriverConfiguration($config)
            ->withDriver('default', 'neo4j+s://localhost')
            ->build();
```

**Comment by mahruqs** [comment]
Thanks so much for the update Ghlen. I will have some time to test it out tomorrow.  Will keep you posted.

**Comment by mahruqs** [comment]
Hi @transistive! That worked like a charm. I am worried about the potential security issues, so will only be using this library for testing the Neo4j database. I'll probably go into production if we do end up using the AuraDB for our product (and only if I am able to securely connect to the AuraDB. 

Thanks again for your timely help! Appreciate it. I will close the issue.

**Comment by transistive** [comment]
Hello @mahruqs,

Thank you for the feedback! Do you have a colleague by any chance who can test it out as well?

I feel quite confident the library will work in production on a standard Linux server, which would alleviate the security concerns.

Kind regards,

Ghlen

**Comment by mahruqs** [comment]
Hi @transistive , I don't have any colleague at this time (as I am the sole developer). I will be putting my app up on AWS over the next few weeks. I'll let you know that goes if we do integrate with AuraDB.

Good to hear the library will be secure on a standard linux server -- that's really good to hear. Thank you so much for your help with this. You shoudl be hearing from me over the next couple of weeks.
