### ISSUE TITLE
Building the query statement from Node, Relationship classes

### ISSUE THREAD

**Issue by danve** [neo4j-php/neo4j-php-client#98]
For cases when adding data to database, would be useful to build the query statements using existing Node and Relationship classes.

User's data are submitted via UI and those data should be convertible into a Node object.
But I noticed that Node class (not only) has no setters.

Would be nice to have the option to take submitted user data, convert them into Node object then build query statements with those Node & Relationship classes instead of writing a dedicated statement for each case of adding new node in database.  

A quick solution would be extending Node class with setters then wrap it into a query builder class which would convert Node data into Cypher query statement

Something resembling the Eloquent way (kind of): model instantiation -> populating -> saving.  

Thanks for your work

**Comment by transistive** [comment]
Hello @danve,

Thank you for the suggestion! Can you elaborate with an example?

Structural types, such as Nodes and Relationships cannot be used as parameters: https://neo4j.com/docs/cypher-manual/current/syntax/values/#structural-types. 

We are working on building neo-eloquent, but these mappings are only guaranteed to work if the library is allowed to maintain custom ID properties, as the internal IDs are not guaranteed to stay the same in the database.

**Comment by danve** [comment]
Hi @transistive 

Even having some experience with mysql,  I am relative new with Cypher & graph db.

So, trying to make use of the ideas of abstraction that an ORM (eg Eloquent, QueryBuilder) is offering, I thought I might replicate the generating of query sentences using objects not concatenating strings and variables.

Obviously, Node class on php side are not pushed to cypher execution space, they are not compatible, I guess (as in mysql) a string representing the query is pushed for execution to the database.
My thinking is like this:
`$_POST -> php variables -> php class (Node or other name) -> generate Cypher query -> Neo4j query execution -> Neo4j Cypher node (or whatever the query was plan to do)` 

At this moment I don't have an example yet, as I am studying your library to see what I can do with it beyond readme.

But I can try an exercise here:

1. a form is presented to the user to register a new Product (already we have a Label: Product)
2. the user fill in a predefined set of attributes (then we have the node's attributes)
3. there may be indicated a connection with a category and named one picked up (here we have a Relation to another node of Label:Category even with an attribute 'name')  
4. after submit there is to generate the Cypher query concatenating cypher syntax and request() variables: 
```"CREATE (:" . request('product_label') .  "  {title: " . request('title') . "})-[:BELONGS_TO]->(:" . request('category_label') . "{ name: " . request('category_name')  . " ".)"```

What if we could feed all the request() variables into an object (as Model in Eloquent) and that model should do the query string build for us? After that calling the client object running the transactions.

Maybe there is already a solution? I don't now yet. You say something about a 'neo-eloquent'.  It is there a preview or details about it? it sounds exciting, I'll wait for it, meanwhile I'll improvise just not to remain stuck in my project.


About ids, yes you are right. I'm in favor of manually setting the id with UUID as node attribute, as the id in Neo4j is not managed the same as in sql world.

Thank you so much for your time,

**Comment by transistive** [comment]
Hello @danve,

Actually, it is this project: https://github.com/Vinelab/NeoEloquent. In fact, you can already use it, but it is not very stable yet for the newer versions.

Thank you for your patience. I will close the issue now :+1:
